leader_19/recomendation/app/urls.py
from django.urls import path
from . import views

app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('catalog/', views.catalog, name='catalog'),
    path('search/', views.search, name='search'),
    path('test/', views.test, name='test'),
    path('results/', views.results, name='results'),

]

leader_19/recomendation/recomendation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
]

leader_19/recomendation/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserId(AbstractUser): 
    added_at = models.CharField(max_length=255) #дата создание личного дела 
    birth_date = models.DateField() # дата рождения
    sex = models.CharField(max_length=10) 
    address = models.CharField(max_length=255)  
   # is_banned = models.BooleanField(default=False)
  

class Profile(models.Model):
    username = models.IntegerField(default=0)
    test_result = models.IntegerField(default=0)

    objects = models.Manager()
 
    def __str__(self):
            return self.id


class Question(models.Model):
    question_text = models.CharField(max_length = 255, default=0)
    objects = models.Manager()

    def __str__(self):
            return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 255)
    votes = models.IntegerField(default = 0)

    objects = models.Manager()

    def __str__(self):
            return self.choice_text

leader_19/recomendation/app/forms.py
from django import forms
from django.forms import ModelForm
from .models import UserId, Choice, Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password

class UserIdCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = UserId
        fields = ('username', 'added_at', 'sex', 'address', 'birth_date')

class UserIdChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = UserId
        fields = ('username', 'added_at', 'sex', 'address','birth_date')


class AnswerForm(forms.Form):
    username = forms.CharField(max_length=64)
    test_result = forms.CharField()
    
 #   def clean(self, *args, **kwargs):
  #      username = self.cleaned_data['username']
   #     try:
    #        user = UserId.objects.get(username=username)
     #   except User.DoesNotExist:
      #      raise forms.ValidationError('Такого пользователя не существует') 
       # return super(AnswerForm, self).clean(*args, **kwargs)

    def save(self):
        profile = Profile.objects.create(**self.cleaned_data)
        profile.save()
        return profile


 

leader_19/recomendation/app/views.py
from django.template import loader
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect, Http404, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.response import TemplateResponse
from django.contrib.auth import authenticate, login, logout

from .models import Question, Choice, UserId, Profile
from .forms import AnswerForm


def home(request):
	return render(request, 'app/home.html')

def catalog(request):
	return render(request, 'app/catalog.html')

def search(request):
	return render(request, 'app/search.html')

def results(request):
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse ('Ожидайте ответа...')
    else:
        form = AnswerForm()
    return render(request, 'app/results.html', {
        'form': form,
        'user': request.user,
        'session': request.session,
    })

    
def vote(request, id):
    question_list = Question.objects.all()
    for question in question_list:

        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist): 
            return render(request, 'app/test.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
        })
        else:
            selected_choice.votes += int (request.GET['votes'])
            selected_choice.save()
    return HttpResponseRedirect(reverse('app:results'))


def test(request):
    choice = Choice.objects.all()
    question_list = Question.objects.all()
    paginator = Paginator(question_list, 1)
    page = request.GET.get('page')

    try:
        question = paginator.page(page)
    except PageNotAnInteger:
        question = paginator.page(1)
    except EmptyPage:
        question = paginator.page(paginator.num_pages)
    return render(request, 'app/test.html', {'question': question, 'page': page, 'choice': choice})

leader_19/recomendation/templates/app/catalog.html
                                                                     
{% extends 'base.html' %}
{% block content %}
<h1 class ="text-center mb-3">Каталог: НЕ ДОДЕЛАНО</h1>
{% endblock %}

leader_19/recomendation/templates/app/home.html
{% extends 'base.html' %}
{% block content %}

<div class ="card text-center">
        <div class ="card-body">
                <h1>Добро пожаловать на рекомендательный сервис "Московское долголетие"</h1>

        <p>Выберите опцию:</p>

                <a class ="btn btn-dark" href ="{% url 'app:test' %}">
                        Пройти тест</a>
                <a class ="btn btn-dark" href ="{% url 'app:catalog' %}">
                        Каталог занятий</a>
                <a class ="btn btn-dark" href ="{% url 'app:search' %}">
                        Поиск занятий</a>


        </div>
    </div>

{% endblock %}

leader_19/recomendation/templates/app/pagination.html
<div class="pagination">  
 <span class="step-links">  
  {% if page.has_previous %}  
      <a href="?page={{ page.previous_page_number }}">Предыдущий</a>  
  {% endif %}  
    <span class="current">  
  Вопрос {{ page.number }} of {{ page.paginator.num_pages }}.  
    </span>  
  {% if page.has_next %}  
        <a href="?page={{ page.next_page_number }}">Следующий</a>  
  {% endif %}  
  </span>  
</div>

leader_19/recomendation/templates/app/results.html
                                                                  
{% extends 'base.html' %}
{% block content %}


<div class="row">
<div class="col-6">
<h1 class ="text-center mb-3">Для корректной работы сервиса:</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn-success">Хочу рекомендации!</button>
</form>


</div>
</div>

{% endblock %}

leader_19/recomendation/templates/app/search.html
                                                                         
{% extends 'base.html' %}
{% block content %}
<h1 class ="text-center mb-3">Search: НЕ ДОДЕЛАНО</h1>
{% endblock %}

leader_19/recomendation/templates/app/test.html
{% extends 'base.html' %}
{% block content %}


{% if error_message %}
<p class ="alert alert-danger">
        <strong>{{ error_message }}</strong>
</p>
{% endif %}


<div class="row"> 
<div class="col-6">
        <form  method ="post">
        {% csrf_token %}
        {% for question in question %}
        {{ question.question_text }}
        <form  method ="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <div class ="check-form">
                <input type ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
                        value ="{{ choice.votes }}" />
                <label for ="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
       
 </div>

           {% endfor %}
        </form>
        {% endfor %}
        </form>

    </div>
</div>


  {% include "./pagination.html" with page=question %} 

{% endblock %}

leader_19/recomendation/templates/base.html
<!doctype  html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
    <title>{% block title %}Московское долголетие: сервис рекомендаций{% endblock %}</title>
    {% block extrahead %} {% endblock %}

</head>
<body>
    <!--NavBar-->
    {% include 'partials/_navbar.html'%}
        <div class ="container">
                                {% block content %}{% endblock %}
        </div>

        </div>
<script type="text/javascript" src='/home/leader_19/recomendation/public/js/main.js'></script>
</body>
</html>

leader_19/recomendation/templates/partials/_navbar.html
<nav class ="navbar navbar-dark bg-success mb-4">


	<div class ="container">
		<a class ="navbar-brand" href ="https://www.mos.ru/city/projects/dolgoletie/">Московское долголетие</a>

	</div>

    {% load static %}
    <link rel="icon" type="image/png" sizes="50x50" href="{% static 'app/images/favicon.png' %}">

</nav>


<!--
<div class="collapse navbar-collapse " id="navbarSupportedContent">
     <ul class="navbar-nav mr-4">
       
       <li class="nav-item">
         <a class="nav-link" href="https://www.mos.ru/city/projects/dolgoletie/">About</a>
       </li>
       <li class="nav-item">
         <a class="nav-link " href="app/test">Portfolio</a>
       </li>
       <li class="nav-item">
         <a class="nav-link " href="#">Team</a>
       </li>
       <li class="nav-item">
         <a class="nav-link " href="#">Post</a>
       </li>
       <li class="nav-item">
         <a class="nav-link " href="#">Contact</a>
       </li>
     </ul>
     
   </div>
-->